### ISSUE TITLE
ProfessorPage To-do List

### ISSUE THREAD

**Issue by InSange** [wkdghdwns199/mini_lms#1]
- [ ] professor 페이지 전환 시 교수 정보 바탕으로 과목 불러오기
- [ ] 교수 정보에 따른 사진 및 이름 데이터 업데이트하기
- [x] 출석 체크 버튼시 전달하고자하는 데이터 선별 후 attendancePage로 전달하기
- [ ] 강의 등록 전환시 교수 정보 전달
