### ISSUE TITLE
AttendancePage To-do List

### ISSUE THREAD

**Issue by InSange** [wkdghdwns199/mini_lms#2]
- [ ] 모달창 중앙으로 옮기기
- [x] 과목 ID로 class_student 테이블과 student 테이블을 참조하여 학생 목록 업데이트하기
- [ ] 출석 인정시간 ~ 지각 인정시간 처리하기
- [ ] 학생들 출석 상태 정보 받아오기 -> 신호를 어떻게 받아서 페이지를 실시간으로 갱신할 것인가..?
- [ ] 출석 결과 저장하기
- [ ] 닫기 -> 인정시간 및 지각 인정시간 지난 후 자동으로 출석 결과 저장하기
- [ ] 출석 시작 버튼 누를시 출석번호 랜덤으로 띄우기
